ALTER TABLE ai_processing ADD COLUMN IF NOT EXISTS processing_stage VARCHAR(50) DEFAULT 'queued';
ALTER TABLE ai_processing ADD COLUMN IF NOT EXISTS retry_count INTEGER DEFAULT 0;
ALTER TABLE ai_processing ADD COLUMN IF NOT EXISTS max_retries INTEGER DEFAULT 3;
ALTER TABLE ai_processing ADD COLUMN IF NOT EXISTS last_error_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE ai_processing ADD COLUMN IF NOT EXISTS worker_pid INTEGER;
ALTER TABLE ai_processing ADD COLUMN IF NOT EXISTS stage_history JSONB DEFAULT '[]'::jsonb;
